### ISSUE TITLE
combine the TSV and JSON configuration files into one of any format

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/metadata-for-user-facility-template-transformations#2]

**Comment by mslarae13** [comment]
Not sure what this issue is or is for? Can we close this??

**Comment by turbomam** [comment]
Yeah, we can close it. I would say now that I have a more general concern for NMDC that we frequently have ETL or dumping projects with multiple input or configuration files in multiple different formats. I'm advocating that we switch overall to a smaller number of config files in a smaller number of formats.
