### ISSUE TITLE
suggested updates to the documentation

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/metadata-for-user-facility-template-transformations#31]
Learning how to run MUTTs with @sujaypatil96 I have some suggestions for the readme page for this repo.

## Software Requirements
1. [poetry](https://python-poetry.org/) ## I found this site to be more helpful https://python-poetry.org/docs/#installing-with-the-official-installer 
3. Python 3.9 ## add link

## Setup

1.  Clone this repo

```
git clone https://github.com/microbiomedata/metadata-template-transformation.git
```

2. Install dependencies with poetry

```
poetry install
```

3. Cookie access to the submission portal is required and can be provided by editing the .env file. Requires you be an individual with appropriate access to the submission you're transforming.
- 1.  When in the NMDC data portal or submission portal, right click & select 'Inspect'
- 2. In the 'Application' menu, select 'Local Storage', specifically, the storage for the NMDC portal
- 3. For the  'Storage Refresh Token' copy the 'Value'
- 4. Edit your .env file and add this value to the file. This should read 
```
DATA_PORTAL_COOKIE = {value}
```

4. Run `etl.py` with options as follows:

```bash
➜  metadata-template-transformation git:(main) ✗ poetry run python etl.py --help                                          
Usage: etl.py [OPTIONS]

Options:
  -o, --output TEXT           Path to result output XLSX file.  [required]
  -m, --mapper PATH           Path to user facility specific JSON file.
                              [required]
  -h, --header / --no-header  [default: no-header]
  -u, --user-facility TEXT    User facility to send data to.  [required]
  -s, --submission TEXT       Metadata submission id.  [required]
  --help                      Show this message and exit.
```
- Example- JGI
```
poetry run python etl.py --submission {UUID of the target submission} --user-facility jgi_mg --mapper input-files/jgi_mg_header.json --output file-name_jgi.xlsx
```
- Example- EMSL
```
poetry run python etl.py --submission df1d2ba5-33be-43d0-b4b9-e5d57ace3f70 --user-facility emsl --mapper input-files/emsl_header.json --output file-name_emsl.xlsx 
```

**Comment by mslarae13** [comment]
Made a PR. Need @sujaypatil96 to review the PR

**Comment by ssarrafan** [comment]
@sujaypatil96 can you please review this PR. I'll move through one more sprint.
