### ISSUE TITLE
rename `--unique-field` to `--sample-id-field`?

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/metadata-for-user-facility-template-transformations#36]

**Comment by mslarae13** [comment]
It's not sample ID, it's samp_name. And I think the point here is WHAT field is unique could change? Though I doubt it will.
I don't think we need to make this change.

**Comment by turbomam** [comment]
When you say 

> It's not sample ID, it's samp_name

what is the it that you're talking bout?

**Comment by turbomam** [comment]
Code location: https://github.com/microbiomedata/metadata-for-user-facility-template-transformations/blob/ee515ffbe7dd4f44dd513812b6d1d53a9106c1f2/etl.py#L241

**Comment by turbomam** [comment]
I trust your judgement for closing the issue, I just don't think anybody in the future would understand your response (or maybe my initial post either)
